# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: dk.ehealth.sundhed.fhir.ig.core
canonical: http://ehealth.sundhed.dk/fhir
name: FUT
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html

dependencies:
  #hl7.fhir.us.core: 3.1.0
  #hl7.fhir.us.davinci-deqm
  #hl7.fhir.au.base
  dk.fhir.ig.dk-core: current